### ISSUE TITLE
Shiftplans are not overwritten

### ISSUE THREAD

**Issue by pejo-sag** [SoftwareAG/oee-simulators#34]
Currently when already having shiftplans posted for the locations, they won't be overwritten. So it throws a warning and continues to simulate. This warning can be seen in the debug log.
It might be useful to delete the shiftplans and deploy the ones included in the simulator.

**Comment by mvoigt-sag** [comment]
- if we plan to do that, we should add another option in the tenant options
- default should be the current behavior (do not overwrite)
