### ISSUE TITLE
Setup CI workflow

### ISSUE THREAD

**Issue by thomaswinkler** [SoftwareAG/oee-simulators#4]
> [<img alt="twi" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.softwareag.com/twi) **Authored by [twi](https://github.softwareag.com/twi)**
_<time datetime="2021-09-02T11:02:01Z" title="Thursday, September 2nd 2021, 1:02:01 pm +02:00">Sep 2, 2021</time>_

---

Build via Github actions.

**Comment by pejo-sag** [comment]
Done with: https://github.com/SoftwareAG/oee-simulators/pull/30
